CREATE TABLE IF NOT EXISTS formulas(
    id int generated by default as identity primary key,
    full_name varchar(100) not null,
    normalized varchar(255) not null,
    expression varchar(255) not null,
    date timestamp not null default now()
);

INSERT INTO formulas (full_name, normalized, expression, date)
VALUES
    ('Formula1','\left(a + b\right)^{2} = b^{2} + \left(a^{2} + 2 a b\right)','(a + b)^2 = a^2 + 2ab + b^2','2024-12-15 10:06:11.944256'),
    ('Formula2','\left(a - b\right) \left(a + b\right) = a^{2} - b^{2}','a^2 - b^2 = (a - b)(a + b)','2024-12-15 10:06:11.944256'),
    ('Formula3','S = \pi r^{2}','S = \pi r^2','2024-12-15 10:06:11.944256'),
    ('Formula4','c^{2} = a^{2} + b^{2}','a^2 + b^2 = c^2','2024-12-15 10:06:11.944256'),
    ('Formula5','bar x = \frac{x_{n} + \left(cdots + \left(x_{1} + x_{2}\right)\right)}{n}','\\bar{x} = \frac{x_1 + x_2 + \cdots + x_n}{n}','2024-12-15 10:06:11.944256'),
    ('Formula6','S_{n} = \frac{n}{2} \left(a_{1} + a_{n}\right)','S_n = \frac{n}{2}(a_1 + a_n)','2024-12-15 10:06:11.944256'),
    ('Formula7','V = \frac{4}{3} \pi r^{3}','V = \frac{4}{3} \pi r^3','2024-12-15 10:06:11.944256'),
    ('Formula8','\sin{\left(a + b \right)} = \sin{\left(a \right)} \cos{\left(b \right)} + \sin{\left(b \right)} \cos{\left(a \right)}','\sin(a + b) = \sin a \cos b + \cos a \sin b','2024-12-15 10:06:11.944256'),
    ('Formula9','\frac{\partial}{\partial x} x^{n} = n x^{n - 1}','\frac{d}{dx} x^n = n x^{n-1}','2024-12-15 10:06:11.944256'),
    ('Formula10','x = \frac{\left(-1\right) b \sqrt{D} pm}{2 a}','x = \frac{-b \pm \sqrt{D}}{2a}','2024-12-15 10:11:20.629524');